name: lfg_bot
description: Open-source Discord LFG bot.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:

  # bot core
  nyxx: ^6.0.3

  # platform
  path_provider: ^2.1.1
  path: ^1.9.0
  io: ^1.0.4

  # database
  drift: ^2.14.0
  sqlite3: ^2.2.0

  # utils
  l: ^4.0.2

  # localization
  intl: ^0.18.1
  intl_translation: ^0.18.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  build_runner: ^2.4.7
  drift_dev: ^2.14.0

