name: lfg_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  nyxx: ^6.0.0
  schedulers: ^1.0.1
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.17
  path_provider: ^2.1.1
  path: ^1.8.3
  io: ^1.0.4
  intl: ^0.18.1
  l: ^4.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  build_runner: ^2.4.6
  drift_dev: ^2.13.0

