name: omega
description: Open-source Discord LFG bot.
version: 1.0.0
repository: https://github.com/Tembeon/lfg_bot

environment:
  sdk: '>=3.4.3 <4.0.0'

# Add regular dependencies here.
dependencies:

  # bot core
  nyxx: ^6.3.1

  # platform
  path: ^1.9.0
  io: ^1.0.4

  # database
  drift: ^2.18.0
  sqlite3: ^2.4.4

  # utils
  l: ^4.0.2
  meta: ^1.15.0

  # localization
  intl: ^0.19.0
#  intl_translation: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  build_runner: ^2.4.11
  drift_dev: ^2.18.0

